name: FoodApp
description: A food tracker app

environment:
  sdk: "^3.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  http: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  flutter_local_notifications: ^13.0.0
  intl: ^0.18.0
  crypto: ^3.0.1
  fluttertoast: ^8.0.8
  flutter_svg: ^1.0.0
  cached_network_image: ^3.2.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
